### PR TITLE
fusehad: Change Makefile so we can see actual pkg-config output

### PR DESCRIPTION
**Pull request by paulwratt**
shows the output of `pkg-config fuse ..` instead or _that_ text.

### CODE REVIEW

**Comment by wd5gnr** [comment]
I'm unclear on this patch: it looks like you added some text from Hackaday into the readme with a link (that's fine) and changed backticks to $(shell in the makefile where pkg-config is called. How does that make it visible?

Oh, I didn't notice this was a fix for the 2.9 branch. I see now. But wait this is against mater and not Fuse 2.9 -- was that what you meant?

**Comment by paulwratt** [comment]
Duwh, yeah the readme was pushed after the initial PR. There should only be the one `Makefile` change.

**Comment by paulwratt** [comment]
the [README.md](https://github.com/wd5gnr/Fusepp/tree/Fuse-2.9/fusehad) is text from the Article that pertains to the project, as opposed the the "whole Article" - There is already one in the `Fuse-2.9` PR you merged (sorry I missed the double push that affected the PR - the `fusehad/` push was supposed to be a seperate PR)

**Comment by paulwratt** [comment]
Before the PR
```
$ make clean; make
rm -rf HaD .obj
g++ -c -Wall --std=c++14 `pkg-config fuse --cflags` -I.. HaD.cpp -o .obj/HaD.o
g++ -MM -Wall --std=c++14 `pkg-config fuse --cflags` -I.. HaD.cpp > .obj/HaD.d
g++ -c -Wall --std=c++14 `pkg-config fuse --cflags` -I.. HaDFS.cpp -o .obj/HaDFS.o
g++ -MM -Wall --std=c++14 `pkg-config fuse --cflags` -I.. HaDFS.cpp > .obj/HaDFS.d
g++ .obj/HaD.o .obj/HaDFS.o `pkg-config fuse --libs` -o HaD
```

After the PR
```
$ make clean; make
rm -rf HaD .obj
g++ -c -Wall --std=c++14 -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I.. HaD.cpp -o .obj/HaD.o
g++ -MM -Wall --std=c++14 -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I.. HaD.cpp > .obj/HaD.d
g++ -c -Wall --std=c++14 -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I.. HaDFS.cpp -o .obj/HaDFS.o
g++ -MM -Wall --std=c++14 -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I.. HaDFS.cpp > .obj/HaDFS.d
g++ .obj/HaD.o .obj/HaDFS.o -lfuse -pthread -o HaD
```

(cleaned up the `...` adendum in the 1st comment)

**Comment by paulwratt** [comment]
Probably should not stay up so late past my bedtime, sorry for the "regmarol".

**Comment by wd5gnr** [comment]
No worries. Thanks for the fixes.

**Pull request merged**
