### PR TITLE
Fuse-2.9: remove boost dependancy from Fuse.h

### PR DESCRIPTION
**Pull request by paulwratt**
Tested and verified, reused code from Fuse3 refactor to remove the
dependancy on '#include <boost/noncopyable.hpp>' in 'Fuse.h'.

(I already submitted this to the main repo - incase that takes a while to be processed, this will allow the next PR on this branch - being the `fusehad/` folder)

### CODE REVIEW

**Comment by paulwratt** [comment]
see this post in Issues (yeah, GH does _not_ allow Issues on _Forked Repos_):
https://github.com/jachappell/Fusepp/issues/7

**Comment by wd5gnr** [comment]
Thanks, that's a good idea.

**Comment by paulwratt** [comment]
Cool, I did want to make them seperate PR, but its done now, thanks (other one is fixed for `Makefile` only) - I still need to fix it for the `jachappell` repo, whoops ..

**Comment by paulwratt** [comment]
BTW were you interested in having this example pushed to the main repo? I dont expect any action over there any time soon, but he might be interested

**Comment by wd5gnr** [comment]
If they want it, they are welcome to it. It would be a nicer example if I made it refetch the feed every once in a while and maybe even allowed the feed to be a command line argument (along with the refresh rate). But it served its purpose for me which was to show an example for Linux-Fu.

**Comment by paulwratt** [comment]
I was wondering the same about the refresh, if I get around to doing something about it I can submit a PR but I dont know how that would affect the continuity with the Article.

Anyway I have some other projects I wanted to try becuase of the extra functionality provided in your example (over the included one), and the 1st one _will_ need a refresh timer, or a "pull on `ls`" so I might get to it sooner rather than later

Anyways, Cheers, and thanks again for the Article, very cool (and simple)

**Comment by wd5gnr** [comment]
Well you could always branch a new version if you are worried about the article continuity, but honestly, I think even tagging it as a release would work.

**Pull request merged**
